name: Build Neuroconductor latest release image from adigherman/neuro-base-xenial

on: [push]

jobs:
  github:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Free up space
        if: success()
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        shell: bash

      - name: Build neuroconductor release image
        if: success()
        run: |
          wget https://raw.githubusercontent.com/adigherman/docker/master/neuroconductor-release/Dockerfile -O Dockerfile 
          docker build -t adigherman/neuroconductor-release:latest - < Dockerfile
        
      - name: Push to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push adigherman/neuroconductor-release:latest