name: Build Neuroconductor base image with Neurodocker

on: [push]

jobs:
  github:
    runs-on: ubuntu-16.04    
    steps:
      - uses: actions/checkout@v1

      - name: Login to github registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Install neurodocker
        if: success()
        run: |
          python -m pip install neurodocker
          neurodocker --help
        shell: bash
        
      - name: Build xenial image
        if: success()
        run: docker run --rm repronim/neurodocker:0.7.0 generate docker \
              --pkg-manager apt \
              --base ubuntu:xenial \
              --ants version=2.3.1 \
              --fsl version=6.0.3 \
              --afni version=latest \
              | docker build -t adigherman/neurodocker:xenial -
        
      - name: Push to docker hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push adigherman/neurodocker:xenial